### ISSUE TITLE
@ mention is broken in case of names with accents on python 2

### ISSUE THREAD

**Issue by pasja** [wee-slack/wee-slack#747]
Hello,

I use 85426cb and realized that my previous tests were not enough to prevent the breakage of @ mention with accented names.

Please see my screenshot attached where the first and third comment were made via wee-slack and the second one with the browser client.
There you can see the missing highlighting on the first case and the working ones on the second and the third case.

![slack-mention](https://user-images.githubusercontent.com/472806/73949724-1b494800-48fb-11ea-907d-c1f5bdd22766.png)

**Comment by pasja** [comment]
After some careful checking it seems that the accents are ok, but having spaces in the names are not.
I will try to investigate it a little bit deeper by adding some dbg prints to linkify_text and see what we are getting and sending there.

**Comment by trygveaa** [comment]
Hm, spaces should be stripped out from the nick in wee-slack. Do you mean that the nick has spaces in the web client, in wee-slack or that you type it with spaces?

**Comment by pasja** [comment]
Yes, most of the nicks in my enterprise workspace has spaces :-) (Sadly this is not configurable, as the names comes from the central directory.) and that is handled correctly by the web client.
If wee-slack strips it then we have found the problem, as I guess that nothing will match the stripped name in `usernames` dict when we are linkifying the text.

**Comment by trygveaa** [comment]
Well, the spaces should be stripped from everywhere in wee-slack, so the usernames dict should contain nicks without spaces.

**Comment by trygveaa** [comment]
Or did you mean that the name you typed won't match the stripped name? You have to type nicks without spaces. That is what tab-completion will give you, and that is also the way the nicks are shown in wee-slack.

**Comment by pasja** [comment]
Sorry for the long silence, I finally managed to work on this.

First let me clarify on the reproduction:

* working case:
at-mention somebody from the web ui by using its auto-completion.
this works well, even if the user has spaces or accented characters in his name.

* not-working case:
at-mention somebody from wee-slack by using its tab-completion.
This is not working, I have got the whole message (with the username) as plain-text.

In order to debug this I have created a simplistic patch what you can see below:

```diff --git a/wee_slack.py b/wee_slack.py
index cbc492b..49a7a9e 100644
     @utf8_decode
@@ -3175,6 +3177,10 @@ def linkify_text(message, team, only_users=False):
     def linkify_word(match):
         word = match.group(0)
         prefix, name = match.groups()
+        with open('/tmp/debug.log', 'a+') as log_file:
+            json.dump(usernames, log_file, indent=4)
+            json.dump(name, log_file, indent=4)
+
         if prefix == "@":
             if name in ["channel", "everyone", "group", "here"]:
                 return "<!{}>".format(name)
```

Based on that I can confirm that the usernames and ids are in a good format in the map, I have got mine like this: `"J\u00e1nosP\u00e1sztor(jpasztor)" : UXXXXXXXX` which is a valid unicode json representation of my nick.

However when I dump the `name` variable I only get a capital j letter `"J"` and nothing else.

Based on that I think that we have some encoding error here, this is why the `name` variable does not match anything from the `usernames` map, hence the issue.

**Comment by pasja** [comment]
I have done a second round of testing with the `pprint` module in order to avoid issues with json encode/decode and the results are the same.

Also I just spotted that in the main weechat buffer I am getting some unicode related tracebacks.
It might be related so I just copy it here:

```
14:51 python: stdout/stderr (slack): Traceback (most recent call last):
14:51 python: stdout/stderr (slack):   File "/home/pasja/.weechat/python/autoload/wee_slack.py", line 678, in handle_next
14:51 python: stdout/stderr (slack):     EVENTROUTER.handle_next()
14:51 python: stdout/stderr (slack):   File "/home/pasja/.weechat/python/autoload/wee_slack.py", line 669, in handle_next
14:51 python: stdout/stderr (slack):     self.proc[function_name](j, self, team, channel, metadata)
14:51 python: stdout/stderr (slack):   File "/home/pasja/.weechat/python/autoload/wee_slack.py", line 3028, in process_reply
14:51 python: stdout/stderr (slack):     process_message(original_message_json, eventrouter, team=team, channel=channel, metadata={})
14:51 python: stdout/stderr (slack):   File "/home/pasja/.weechat/python/autoload/wee_slack.py", line 2893, in process_message
14:51 python: stdout/stderr (slack):     dbg("NORMAL REPLY {}".format(message_json))
14:51 python: stdout/stderr (slack): UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 19: ordinal not in range(128)

```

**Comment by trygveaa** [comment]
Okay, I can reproduce the issue with accents in nicks when using python 2 (it works with python 3).

I can't reproduce the `UnicodeEncodeError` though. Does that happen in master without your logging statements too? Can you check what `message_json` contains?

**Comment by trygveaa** [comment]
In your second comment you said that accents works and it is spaces which causes the issue. This was incorrect, or?

**Comment by pasja** [comment]
> In your second comment you said that accents works and it is spaces which causes the issue. This was incorrect, or?

Yes that was incorrect. It turned out that only those have spaces in their names who have other unicode characters as well.

**Comment by pasja** [comment]
> I can't reproduce the `UnicodeEncodeError` though. Does that happen in master without your logging statements too? Can you check what `message_json` contains?

It happens without my patch. I have reverted them, set `plugins.var.python.slack.debug_level` to `0` and `plugins.var.python.slack.debug_mode` to `true` and got the exception with upstream wee-slack

Will check `message_json` for you soon.

**Comment by trygveaa** [comment]
That commit should fix the issue.

But please check `message_json` nevertheless (the `UnicodeEncodeError` you saw is probably not affected by that commit), as I'm interested to see why that occurs, and if it causes any bugs.

**Comment by pasja** [comment]
Please see the dump of `message_json` below.
```
{
    "text": "@J\u00e1nosP\u00e1sztor(jpasztor): rerere", 
    "team": "TXXXXXXXX", 
    "type": "message", 
    "user": "UXXXXXXXX", 
    "ts": "1582902167.003800"
}
```
This was created before applying your patch.
You were correct, after applying the patch, this message remains the same.

The original issue was solved by having the patch, thanks for it!

**Comment by trygveaa** [comment]
Hm, still doesn't make sense to me. Can you log `type("NORMAL REPLY {}")` and `type(message_json)` on the line above `dbg("NORMAL REPLY {}".format(message_json))`?
