### ISSUE TITLE
Breaks weechat-matrix with python 3.9

### ISSUE THREAD

**Issue by wavexx** [wee-slack/wee-slack#812]
So I've found a new "interesting" issue as debian rebuilt weechat with libpython3.9.

As soon as wee-slack connects to a team, weechat-matrix cannot seem to establish any new connection  (read operation did not complete coming from the underlying socket). The same version of wee-slack/matrix can seem to work together fine with libpython3.8.

I assume some module is now changing a global socket/ssl setting that results in this breaking behavior, however I'm having an hard time figuring out what exactly is being changed to fix and/or report the issue.

Loading the module is not enough: as long as slack doesn't autoconnect, it can be loaded together and weechat-matrix can still connect.

Ideas?

**Comment by wavexx** [comment]
Ironically, if I load wee-slack before weechat-matrix, then it's wee-slack that fails.

```
21:00 python: stdout/stderr (slack): Traceback (most recent call last):
21:00 python: stdout/stderr (slack):   File "/home/ydelia/.weechat/python/wee_slack.py", line 167, in wrapper
21:00 python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
21:00 python: stdout/stderr (slack):   File "/home/ydelia/.weechat/python/wee_slack.py", line 579, in receive_ws_callback
21:00 python: stdout/stderr (slack):     handle_socket_error(e, team, 'receive')
21:00 python: stdout/stderr (slack):   File "/home/ydelia/.weechat/python/wee_slack.py", line 574, in receive_ws_callback
21:00 python: stdout/stderr (slack):     opcode, data = team.ws.recv_data(control_frame=True)
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_core.py", line 331, in recv_data
21:00 python: stdout/stderr (slack):     opcode, frame = self.recv_data_frame(control_frame)
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_core.py", line 344, in recv_data_frame
21:00 python: stdout/stderr (slack):     frame = self.recv_frame()
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_core.py", line 378, in recv_frame
21:00 python: stdout/stderr (slack):     return self.frame_buffer.recv_frame()
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_abnf.py", line 361, in recv_frame
21:00 python: stdout/stderr (slack):     self.recv_header()
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_abnf.py", line 309, in recv_header
21:00 python: stdout/stderr (slack):     header = self.recv_strict(2)
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_abnf.py", line 396, in recv_strict
21:00 python: stdout/stderr (slack):     bytes_ = self.recv(min(16384, shortage))
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_core.py", line 453, in _recv
21:00 python: stdout/stderr (slack):     return recv(self.sock, bufsize)
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3/dist-packages/websocket/_socket.py", line 100, in recv
21:00 python: stdout/stderr (slack):     bytes_ = sock.recv(bufsize)
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3.9/ssl.py", line 1226, in recv
21:00 python: stdout/stderr (slack):     return self.read(buflen)
21:00 python: stdout/stderr (slack):   File "/usr/lib/python3.9/ssl.py", line 1101, in read
21:00 python: stdout/stderr (slack):     return self._sslobj.read(len)
21:00 python: stdout/stderr (slack): ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2622)
21:00 =!= python: error in function "receive_ws_callback"
```

Something is fishy here. ssl.SSLWantReadError is handled one catch block earlier, but it's seemingly skipped?

**Comment by liskin** [comment]
> ssl.SSLWantReadError is handled one catch block earlier, but it's seemingly skipped?

```
def recv(sock, bufsize):
    if not sock:
        raise WebSocketConnectionClosedException("socket is already closed.")

    def _recv():
        try:
            return sock.recv(bufsize)
        except SSLWantReadError:
            pass
        except socket.error as exc:
            error_code = extract_error_code(exc)
            if error_code is None:
                raise
            if error_code != errno.EAGAIN or error_code != errno.EWOULDBLOCK:
                raise

        r, w, e = select.select((sock, ), (), (), sock.gettimeout())
        if r:
            return sock.recv(bufsize)

    try:
        if sock.gettimeout() == 0:
            bytes_ = sock.recv(bufsize)
        else:
            bytes_ = _recv()
```

line 100 is `bytes_ = sock.recv(bufsize)`, so the catch block above doesn't apply as `_recv` isn't getting invoked.

**Comment by wavexx** [comment]
So sockets are turning blocking, somehow after loading a second python module? :thinking:

**Comment by wavexx** [comment]
So I spent a few hours yesterday debugging the recv function in websocket.

- Loaded wee-slack, waited for connection
- Loaded matrix.py, connected

Doing this way seemed less annoying than the other way around. I added some print statements in the second try block (at _socket.py:99) to fetch the descriptor ID and show the blocking behavior.

Turns out it doesn't *always* fail, it fails about 1/3 of the time. The descriptor is always the same, and the timeout is also always 0 (i/e non-blocking). Yet, the first branch is still chosen at some point.

I somehow suspect this is a new bad interaction of subinterpreters and external python modules as used by weechat-python with python 2.9. Notice that matrix.py itself cannot be reloaded (psycopg2 directly crashes on reload).

**Comment by jonorthwash** [comment]
> python 2.9.

python 3.9?

**Comment by wavexx** [comment]
> python 3.9?

Yes, typo. Sadly, I after spending some hours on it I couldn't find the issue. I still think it's subprocess-related due to changes in python 3.9, since the same combination/version of the system modules work fine with 3.8.

Does anybody have some experience with the python c API and look at the subprocess initialization in weechat? I'm not 100% sure if the interpreters can be started without locking (as in the case of the weechat python plugin implementation).

**Comment by jonorthwash** [comment]
If this is a regression in Python 3.9 (what it sounds like you're saying, but I could be misunderstanding), perhaps some Python devs would be interested to know?

**Comment by wavexx** [comment]
It is my suspicion, however I'm not familiar enough with the c python API for subinterpreters at this moment to be certain and make a serious report. Involving the author of weechat-python would be a better idea IMHO. As vacations are over, I'm afraid I'll stick to python 3.8 for the moment due to time constraints.

**Comment by vstinner** [comment]
Hi, I'm working on Python upstream and a colleague asked me to look into this issue.

> It is my suspicion, however I'm not familiar enough with the c python API for subinterpreters at this moment to be certain and make a serious report.

What is the relationship between wee-slack and subinterpreters?

I looked into https://github.com/poljar/weechat-matrix/issues/248 but I don't know how to reproduce the issue, please see my comment there: https://github.com/poljar/weechat-matrix/issues/248#issuecomment-797580735

@liskin code implements blocking read on the SSL socket, but the socket seems to be configured in non-blocking mode.

> So sockets are turning blocking, somehow after loading a second python module? thinking

This is really strange and deserves debugging. Should the socket be blocking or not? Why is it changing its blocking mode?

**Comment by vstinner** [comment]
Would it be possible to provide a reproducer for the issue? The bare minimum is to explain how to reproduce the issue in weechat, but the best would be a script reproducing the issue ... without weechat :-)

**Comment by vstinner** [comment]
Aaaah, I found where websocket/_socket.py comes from: https://github.com/websocket-client/websocket-client/blob/df87514c7cbc202e5e469f775daea8c3bf972fff/websocket/_socket.py#L95 It's the https://pypi.org/project/websocket-client/ project.

It seems like https://github.com/wee-slack/wee-slack/issues/812#issuecomment-744061833 traceback comes from websocket-client 0.57.0 (websocket/_socket.py at line 100: `bytes_ = sock.recv(bufsize)`).

```
    try:
        if sock.gettimeout() == 0:
            bytes_ = sock.recv(bufsize)  # <=== HERE: line 100
        else:
            bytes_ = _recv()
```

Is it a deliberate choice to use a non-blocking socket? If yes, you should handle ssl.SSLWantReadError error in the caller.

Note: There is a new websocket-client 0.58.0 release.

**Comment by trygveaa** [comment]
@vstinner: Yes, using a non-blocking socket is deliberate. WeeChat is single threaded, so we have to do that so we don't block it.

We do handle `ssl.SSLWantReadError` here: https://github.com/wee-slack/wee-slack/blob/v2.7.0/wee_slack.py#L575

**Comment by ajdiaz** [comment]
I wrote a quick & dirty workaround to fix the problem (diff below). This is a strange behaviour, the except does not appear to match with the proper exception `SSLWantReadError`, but the general catching exception has the proper class in the value. I need to match the name of the class because apparently classes objects are not "equal".

I also confirmed that is related with non-blocking feature in the ssl socket. Seting blocking to true also allow to connect and read data correctly (but of course blocking weechat).

I do not considerer this a patch, just a dirty test, so I prefer to put the diff here, but if someone wants a proper PR just let me know.

```diff
--- /usr/share/weechat/python/weechat-matrix.py	2021-03-24 13:21:43.000000000 +0100
+++ /tmp/weechat-matrix.py	2021-03-24 19:52:51.787594026 +0100
@@ -270,6 +270,14 @@
             except AttributeError:
                 str_error = str(error)
 
+            if error.__class__.__name__ == ssl.SSLWantReadError.__name__:
+                hook = W.hook_fd(server.socket.fileno(), 1, 0, 0, "ssl_fd_cb",
+                                 server.name)
+                server.ssl_hook = hook
+
+                return False
+
+
             message = ("{prefix}Error while doing SSL handshake"
                        ": {error}").format(
                            prefix=W.prefix("network"), error=str_error)
@@ -298,6 +306,9 @@
             str_error = error.strerror if error.strerror else "Unknown error"
             str_error = errno + str_error
 
+            if error.__class__.__name__ == 'SSLWantReadError':
+                break
+
             message = ("{prefix}Error while reading from "
                        "socket: {error}").format(
                            prefix=W.prefix("network"), error=str_error)
```

**Comment by trygveaa** [comment]
@ajdiaz: The only way I can see the exception not matching the real class is if this is reached: https://github.com/websocket-client/websocket-client/blob/v0.58.0/websocket/_ssl_compat.py#L45

Can you check if that is reached for you?

**Comment by ajdiaz** [comment]
I put a `raise Exception("foobar")` in that line and everything appears to work as usual... Seems that the line is not reached.

**Comment by ajdiaz** [comment]
Another dirty workaround for the same problem inside wee_slack (diff below). I can catch the `SSLWantReadError` exception inside the `receive_ws_callback` function, around the call to `handle_socket_error`. For the same unknown reason, the exception is not properly catched inside that call. Maybe we can add `SSLWantReadError` (and similar) inside `handle_socket_error`?

I hope that this can help to find out the source problem.

```diff
--- /tmp/wee_slack.py	2021-03-27 11:10:32.368228305 +0100
+++ /home/ajdiaz/.weechat/python/autoload/wee_slack.py	2021-03-24 11:50:19.536455383 +0100
@@ -629,8 +629,11 @@
                 # No more data to read at this time.
                 return w.WEECHAT_RC_OK
             except (WebSocketConnectionClosedException, socket.error) as e:
-                handle_socket_error(e, team, "receive")
-                return w.WEECHAT_RC_OK
+                try:
+                    handle_socket_error(e, team, "receive")
+                    return w.WEECHAT_RC_OK
+                except ssl.SSLWantReadError:
+                    return w.WEECHAT_RC_OK
 
             if opcode == ABNF.OPCODE_PONG:
                 team.last_pong_time = time.time()
```

**Comment by trygveaa** [comment]
Hm, that doesn't make any sense? `SSLWantReadError` is already catched in the same try, right above that. Why would it help to catch it again there?

**Comment by ajdiaz** [comment]
Yep, makes no sense in python logic. The underlying problem, as far as I see, is that wee_slack and weechat-matrix exceptions are mixed, so the exception raised in wee_slack (for instance, but could happen in different order) is not an instance of the `ssl.SSLWantReadError` loaded by wee_slack, but for weechat-matrix (and vice-versa).

To confirm this I print the `id` of the class `ssl.SSLWantReadError` of each plugin at the very beginning of the execution, and then when the exception is raised I print the `id(e.__class__)`, where  `e` is the exception object catched in the general case. The output shows that the exception raised is instance of the other plugin class:

```
matrix: id(ssl.SSLWantReadError) = 94327907658960
slack:  id(ssl.SSLWantReadError) = 94327910336544
....
traceback....
slack: id(e.__class__) = 94327907658960
```

This explain why the trick comparing `__name__` (my first workaround) works (both classes has the same name). And also why works the second workaround (because the `handle_socket_error` in this case raise the proper exception).

At this point, I 'm quite confident that the problem is not on wee_slack or matrix plugin, but in some place under them, maybe the weechat python plugin library  or in python itself (maybe related `SSLContext`?). This seems a threading problem with a no thread-safe variable at some point.

I will try to go deeper, but honestly I think that this is not a wee_slack problem anymore, and it's not easy to reproduce in different context.

Maybe @vstinner can put some light on this. If you want to reproduce just install wee_slack.py and weechat-matrix plugin in weechat (both with valid user/pass) and connect. I can reproduce the error with python 3.9.2 and weechat 3.1 (both plugins using git master branch).

**Comment by vstinner** [comment]
I don't know wee_slack nor weechat-matix nor weechat. Do all plugins run in same process? In the same Python interpreter?

Maybe somehow each plugin has its own ssl module instance.

**Comment by trygveaa** [comment]
> Yep, makes no sense in python logic. The underlying problem, as far as I see, is that wee_slack and weechat-matrix exceptions are mixed, so the exception raised in wee_slack (for instance, but could happen in different order) is not an instance of the `ssl.SSLWantReadError` loaded by wee_slack, but for weechat-matrix (and vice-versa).

Ah, nice find.

> This explain why the trick comparing `__name__` (my first workaround) works (both classes has the same name). And also why works the second workaround (because the `handle_socket_error` in this case raise the proper exception).

I don't get why the workaround with `handle_socket_error` works, since that method just re-raises the same exception?

> At this point, I 'm quite confident that the problem is not on wee_slack or matrix plugin, but in some place under them, maybe the weechat python plugin library or in python itself (maybe related `SSLContext`?). This seems a threading problem with a no thread-safe variable at some point.
> 
> I will try to go deeper, but honestly I think that this is not a wee_slack problem anymore, and it's not easy to reproduce in different context.

Yeah, seems like the cause of this issue has to be in either python or the python plugin in weechat.

> I don't know wee_slack nor weechat-matix nor weechat. Do all plugins run in same process? In the same Python interpreter?

@vstinner: As far as I can see, each python script in weechat runs in it's own sub-interpreter, created using [Py_NewInterpreter](https://docs.python.org/3/c-api/init.html#c.Py_NewInterpreter). I see this in the function that loads the script, [here](https://github.com/weechat/weechat/blob/v3.1/src/plugins/python/weechat-python.c#L830).

**Comment by vstinner** [comment]
> @vstinner: As far as I can see, each python script in weechat runs in it's own sub-interpreter, created using Py_NewInterpreter. I see this in the function that loads the script, here.

In that case, how do you end up with an exception raised in a subinterpreter A being used in a subinterpreter B?

I'm referring to:

> The underlying problem, as far as I see, is that wee_slack and weechat-matrix exceptions are mixed

**Comment by trygveaa** [comment]
> In that case, how do you end up with an exception raised in a subinterpreter A being used in a subinterpreter B?

I have no clue. I guess someone will have to look at the python plugin for weechat (the file I linked to) to figure it out. Also keep in mind that I may have misunderstood it.

**Comment by trygveaa** [comment]
Here is a minimal script to reproduce the issue:

```
import socket
import ssl
import weechat

HOST, PORT = "localhost", 1234


def sock_cb(data, fd):
    while True:
        try:
            data = sock.recv(1024)
        except ssl.SSLWantReadError:
            return weechat.WEECHAT_RC_OK
        weechat.prnt("", f"Received: {data}")
    return weechat.WEECHAT_RC_OK


if __name__ == "__main__":
    if weechat.register("ssl_issue_reproducer", "trygveaa", "1.0", "MIT", "", "", ""):
        sock = ssl.wrap_socket(socket.socket(socket.AF_INET, socket.SOCK_STREAM))
        sock.connect((HOST, PORT))
        hook_sock = weechat.hook_fd(sock.fileno(), 1, 0, 0, "sock_cb", "")
        sock.setblocking(False)
```

If you load that script in weechat, and then load another script that imports ssl the issue occurs. E.g. if you run this, it will load the first script, wait 5 seconds and then load a second script which just import ssl:

```
weechat -t -r '/script load <path_to_script>; /wait 5 /eval -s /print Loading second script\; /python eval import ssl'
```

After the second script has loaded, the `__class__` of the `SSLWantReadError` exception has changed so it isn't catched anymore.

That script connects to localhost:1234. To start a server the script can connect to you can run:

```
openssl req -x509 -nodes -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj '/'
while :; do echo test; sleep 1; done | openssl s_server -key key.pem -cert cert.pem -accept 1234
```

@vstinner: Does this help you to figure out where the issue lies?

**Comment by trygveaa** [comment]
To be sure, I tried with Python 3.8 now, and can't reproduce it with that, only with 3.9. I guess this points to the issue being in Python, and not in weechat? @vstinner: Do you know of any changes in Python 3.9 related to this?

**Comment by vstinner** [comment]
> @vstinner: Do you know of any changes in Python 3.9 related to this?

I have no idea. Every Python release introduce tons of changes. Some are listed in https://docs.python.org/3.9/whatsnew/3.9.html some in https://docs.python.org/3.9/whatsnew/changelog.html#changelog and sadly some are not documented when the author considers that it should not have any impact on users.

**Comment by trygveaa** [comment]
@vstinner: I bisected it. The commit that introduces the issue is https://github.com/python/cpython/commit/82c83bd907409c287a5bd0d0f4598f2c0538f34d

**Comment by vstinner** [comment]
`ssl.SSLWantReadError` is the same object or not depending if the `_ssl` module is imported first in the main interpreter or in a subinterpreter.

```
import _testcapi
import os
rfd, wfd = os.pipe()
code = fr"""
import os, ssl
wfd = {wfd}
line = "%#x\n" % id(ssl.SSLWantReadError)
os.write(wfd, line.encode())
"""
if 0:
    # import _ssl in subinterpreter then in main interpreter
    _testcapi.run_in_subinterp(code)
    sub_id = os.read(rfd, 100).decode().rstrip()
    exec(code)
    main_id = os.read(rfd, 100).decode().rstrip()
else:
    # import _ssl in main interpreter then in subinterpreter
    exec(code)
    main_id = os.read(rfd, 100).decode().rstrip()
    _testcapi.run_in_subinterp(code)
    sub_id = os.read(rfd, 100).decode().rstrip()
print(main_id, sub_id, main_id == sub_id)
```

Import in main interpreter, then in subinterpreter:

* Python 3.6-3.10: True (same object)

Import in subinterpreter, then in main interpreter:

* Python 3.6-3.10: False (different object)

I tested Python 3.10.0a6.

The commit https://github.com/python/cpython/commit/82c83bd907409c287a5bd0d0f4598f2c0538f34d is part of Python 3.9.0 and newer.

**Comment by vstinner** [comment]
To debug, try to add `import _ssl` at the first line of your application.

**Comment by vstinner** [comment]
In Python 3.10, the `_ssl` module doesn't use the multi-phase initialization API (PEP 489) yet, and is not fully compatible with sub-interpreters yet.

**Comment by trygveaa** [comment]
> ssl.SSLWantReadError is the same object or not depending if the _ssl module is imported first in the main interpreter or in a subinterpreter.

Is it supposed to behave that way?

I think _ssl is only imported in subinterpreters in this case, since I think one subinterpreter is used per weechat script, and _ssl is only imported from the scripts.

> To debug, try to add import _ssl at the first line of your application.

By application, I assume you mean the main interpreter? Not really sure how to do that. I tried `PyRun_String ("import _ssl", Py_file_input, NULL, NULL);`, but that didn't change anything.

**Comment by trygveaa** [comment]
> By application, I assume you mean the main interpreter? Not really sure how to do that. I tried PyRun_String ("import _ssl", Py_file_input, NULL, NULL);, but that didn't change anything.

Okay, just had the wrong value for globals. When I use this:

```
PyRun_String ("import _ssl", Py_file_input, PyDict_New(), NULL);
```

It does indeed fix the error. So what's the conclusion here? It doesn't seem correct that it's different objects when importing it in the subinterpreter first?

**Comment by vstinner** [comment]
> So what's the conclusion here?

Once all extension modules will be ported to multiphase init, each subinterpreter will get a different ssl.SSLWantReadError object. It's the expected behavior.

More generally, you must never exchange Python objects between interpreters. You must treat them as separated processes, and serialize/deserialize objects between interpreters.

I didn't understand your root issue. I'm just commenting how subinterpreters are supposed to work in Python.

---

All extension modules must be converted to multi-phase init API to be made compatible with subinterpreters.

As I wrote previously, it's not the case for the _ssl module yet: see https://bugs.python.org/issue42333

We made great progress since 2019: https://vstinner.github.io/isolate-subinterpreters.html

> **77% (102/132) of extension modules** use the new multiphase initialization API (PEP 489) on a total of 132 extension modules. For comparison, in Python 3.8, only 23% (27/118) of extensions used the new multiphase initialization API: 75 extensions have been converted in the meanwhile.

**Comment by trygveaa** [comment]
> More generally, you must never exchange Python objects between interpreters. You must treat them as separated processes, and serialize/deserialize objects between interpreters.

So you think that the python plugin in weechat does this?

> All extension modules must be converted to multi-phase init API to be made compatible with subinterpreters.
> 
> As I wrote previously, it's not the case for the _ssl module yet: see https://bugs.python.org/issue42333

You said it's not compatible in 3.10, but we're talking about 3.9? Is it not compatible in 3.9 either, or what do you mean? And what do you mean by not compatible, since it worked fine before 3.9?

**Comment by vstinner** [comment]
Sorry, I cannot reply to your questions since I don't know how weechat uses Python subinterpreters.

**Comment by trygveaa** [comment]
Okay, but can you explain more what you mean by this?

> All extension modules must be converted to multi-phase init API to be made compatible with subinterpreters.

What do you mean that the extension module is not compatible with subinterpreters? Even though _ssl is not converted to multi-phase init API, it should be possible to use it in subinterpreters?

**Comment by trygveaa** [comment]
Here is code to reproduce the issue outside of weechat:

```
#define PY_SSIZE_T_CLEAN
#include <Python.h>

int
main(int argc, char *argv[])
{
    Py_Initialize();

    PyThreadState *interpreter1 = Py_NewInterpreter();
    PyThreadState_Swap(interpreter1);

    char *filename = "subinterpreter_ssl_issue.py";
    FILE *fp = fopen(filename, "r");
    PyRun_SimpleFile(fp, filename);

    PyThreadState *interpreter2 = Py_NewInterpreter();
    PyThreadState_Swap(interpreter2);

    PyRun_String("import _ssl", Py_file_input, PyDict_New(), NULL);

    PyThreadState_Swap(interpreter1);

    PyObject *evMain, *evDict, *evFunc;
    evMain = PyImport_AddModule((char *) "__main__");
    evDict = PyModule_GetDict(evMain);
    evFunc = PyDict_GetItemString(evDict, "read_socket");
    PyObject_CallFunction(evFunc, NULL);
    PyObject_CallFunction(evFunc, NULL);

    if (Py_FinalizeEx() < 0) {
        exit(120);
    }
    return 0;
}
```

The loaded `subinterpreter_ssl_issue.py` file contains this:

```
import socket
import ssl

HOST, PORT = "localhost", 1234


def read_socket():
    try:
        print("data:", sock.recv(10000))
    except ssl.SSLWantReadError:
        print("no data")
    except Exception as e:
        print("unknown error:", e)


sock = ssl.wrap_socket(socket.socket(socket.AF_INET, socket.SOCK_STREAM))
sock.connect((HOST, PORT))
sock.setblocking(False)
read_socket()
```

When I run this with python 3.9 I get:

```
no data
data: b'test\n'
unknown error: The operation did not complete (read) (_ssl.c:2622)
```

While if I run it with python 3.8 I get:

```
no data
data: b'test\n'
no data
```

**Comment by trygveaa** [comment]
@vstinner: Have you had a chance to look at my code to reproduce the issue outside of WeeChat? Unless I'm using the Python/C API wrong, it seems to me like a regression in Python 3.9.

**Comment by vstinner** [comment]
If you consider that it's a Python bug, please report it at https://bugs.python.org/

I'm not available to investigate your issue right now.

**Comment by trygveaa** [comment]
I checked the Python repo again, and the issue was actually fixed a few days after I posted the code to reproduce the issue.

This is the commit that fixed the issue: https://github.com/python/cpython/commit/7f1305ef9ea7234e1a5aacbea17490232e9b7dc2

So it will work fine in Python 3.10. I posted this bug for 3.9: https://bugs.python.org/issue44050

**Comment by wavexx** [comment]
@trygveaa thanks for the big effort of first pinning this down, then reporting this as well. I'm kind of worried that this was fixed by implementing multiphase init, new in 3.9 AFAIK, which means similar kind of issues might await in modules that don't implement this yet :/

**Comment by trygveaa** [comment]
@wavexx: Yes, it was fixed by implementing multi phase init for the _ssl module. But why was multi phase init used in 3.9 if the modules didn't support it yet (if that's the case)?

**Comment by wavexx** [comment]
@trygveaa My wild guess, submodules are so rarely used that nobody cared? When I attempted to debug it at first and was reading through the docs it wasn't (and still isn't) even clear to me if submitting a command to a subinterpreter needs to run with the GIL held or not.

**Comment by trygveaa** [comment]
I have verified that this is fixed in Python >= 3.9.8 and >= 3.10.0, so I'll close this issue.
